default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  pool: 5

development:
  <<: *default
  database: auth_free_development

test:
  <<: *default
  database: auth_free_test

production:
  <<: *default
  database: auth_free_production